### ISSUE TITLE
linky no worky for using deconst client to build RAX branded docs

### ISSUE THREAD

**Issue by sheyman** [rackerlabs/docs-barbican#22]
See https://github.com/rackerlabs/docs-barbican/blob/master/CONTRIBUTING.md#previewing-changes

The link for "instructions for building with the client" takes you to 404 land:

https://github.com/rackerlabs/docs-migration/blob/master/docs/migration-instructions.rst#building-your-project-with-the-local-deconst-client

Unless its something that I don't have access to?

**Comment by meker12** [comment]
@sheyman   I'll update the link.  However, for now, it's better to build the docs locally.  The decoonst client uses docker containers, and people have had a few issues with it.  The Engineering team is working on a solution that will allow you to build the Rackspace-branded docs from a PR, and then view them in the browser.

If you'd like to try the local client, you can find it here;  https://github.com/deconst/client

Do you have access to that link?

**Comment by meker12** [comment]
Closing this. Let me know if you need any additional information.
