### ISSUE TITLE
Configure Environment Variable

### ISSUE THREAD

**Issue by raj-patel** [rackerlabs/docs-barbican#48]
https://developer.rackspace.com/docs/cloud-keep/v1/developer-guide/#configure-environment-variables only applies to CLI. Need to specify that a user using http would have to specify it in http header.

**Comment by sheyman** [comment]
That section is for setting environment variables that are used later on with curl commands.

**Comment by raj-patel** [comment]
Steve,
    I don't see a separate section or anywhere in the individual calls section that tell me what http parameter names i should use.

**Comment by meker12** [comment]
@raj-patel   and @sheyman  I updated the intro section at the beginning of each API operation to include the following note:



**Note:**  These examples use the ``$ENDPOINT`` and ``$AUTH_TOKEN`` environment variables to specify the API endpoint and authentication token values for accessing the service. Make sure you :ref:`Configure environment variables <configure-environment-variables>` before running the code samples.

**Comment by sheyman** [comment]
I think this has been resolved - @raj-patel is this ok to close?
