### ISSUE TITLE
Review accuracy of info about service endpoints

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-barbican#61]
Not sure the information in the [Regionalized service endpoints](https://developer.rackspace.com/docs/cloud-keep/v1/developer-guide/#document-general-api-info/service-access-endpoints) documents the Cloud Keep endpoints accurately.   @sheyman  Can you review?

**Comment by sheyman** [comment]
For now we are just in IAD.  We will be up in other datacenters eventually.

**Comment by meker12** [comment]
Moving this to #69 -- check during refactor.
