### ISSUE TITLE
Strider build

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-barbican#63]
I made the updates to the project to support Strider builds for this repo as described here: https://github.com/rackerlabs/nexus-control/issues/346.  The webhook for Strider needs to have the secret added @smashwilson.

**Comment by smashwilson** [comment]
Done. The build [is here](https://build.developer.rackspace.com/rackerlabs/docs-barbican/) and the webhook looks healthy:

![screen shot 2016-03-16 at 11 28 15 am](https://cloud.githubusercontent.com/assets/17565/13817947/84639856-eb6a-11e5-86bd-c40193588205.jpeg)
