### ISSUE TITLE
Cloud Keep editorial review

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-barbican#65]
@kmsholcomb  Submitting Cloud Keep docs for editorial review.

**Comment by kmsholcomb** [comment]
Hi @meker12. I am finally done! The attached Word doc (and PDF copy of it) contains my suggested edits. Please let me know if you have any questions. Thanks!

[Rackspace Cloud Keep API 1_editsKH.pdf](https://github.com/rackerlabs/docs-barbican/files/198566/Rackspace.Cloud.Keep.API.1_editsKH.pdf)
[Rackspace Cloud Keep API 1_editsKH.docx](https://github.com/rackerlabs/docs-barbican/files/198567/Rackspace.Cloud.Keep.API.1_editsKH.docx)

**Comment by kmsholcomb** [comment]
@meker12: Closing this issue, since I finished it.
