### ISSUE TITLE
QE refactored Cloud Keep content

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-barbican#74]
# Refactor API Guide: QE checklist

Use the following checklist to verify that API guide refactoring for each service. If you have questions, open a [docs-common issue](https://github.com/rackerlabs/docs-common/issues/new).  

Do the QE check against the PR submitted to the master repo.  Ask the person who did the refactoring to make you a collaborator on their fork in case you want to submit a PR to correct something. 

When you build the refactored Sphinx project, use the ``make clean html`` command to build chunked content. 

- [x] Review the [Strider build log](https://build.developer.rackspace.com/) for errors. Notify author about any issues.
- [x] Check for broken links.
- [x] Verify that navigation matches the [API Guide template](https://staging.developer.rackspace.com/staging.horse/build-2ecafb8a99/docs/api-doc-template/).
- [x] Check the *API reference* section to verify that the methods for each resource are in a single topic.
- [x] Check the *General API information* topics to make sure they match the common content where possible.
- [x] Check the *Authentication* topic in the Getting started section to make sure it matches the [common template](https://github.com/rackerlabs/docs-common/blob/master/api-guide-template/getting-started/authenticate.rst).
- [x] Check ``conf.py`` to make sure it has the updates from the 
       [template](https://github.com/rackerlabs/docs-common/blob/master/api-guide-template/conf.py).
- [x] Verify that you can [build locally from source](https://github.com/rackerlabs/docs-rackspace/blob/master/doc/tools/build-from-source.rst).

**Comment by cyrichardson** [comment]
Item 1. Latest build in strider dashboard shows only the warning that many of us are getting from the authenticate.rst file: /getting-started/authenticate.rst:1: WARNING: Could not lex literal_block as "json". Highlighting skipped. This warning does not show up in the local builds.

**Comment by cyrichardson** [comment]
Item 2. Good but would change maxdepth in main index.rst to 3 so that the individual API operations should up in left nav pane. Comment made in PR at location for change.

**Comment by cyrichardson** [comment]
Item 4. LGTM!

**Comment by cyrichardson** [comment]
Item 5. Service access is in the API general information index.rst 2 times. Need to remove one.

**Comment by cyrichardson** [comment]
Item 6. Looks good. One thing to change is example service catalog specific to Cloud Keep. The current example shows Rackspace CDN service catalog info. Comment made at location in PR.

**Comment by cyrichardson** [comment]
Item 7. conf.py looks good.

**Comment by cyrichardson** [comment]
Item 8. Clean local build produced from Margaret's fork/branch.

**Comment by cyrichardson** [comment]
Item 2. Link checking:
-  Get a "Your connection is not secure" for signup link in Limited Availability section: https://staging.developer.rackspace.com/build-32a1c854cc/docs/cloud-keep/v1/developer-guide/limited-availability/

Maybe it has to be this was for LA release - maybe users must request access.

**Comment by cyrichardson** [comment]
@meker12 QE complete. Made inline comments in PR #73 for minor changes.
